name: Diplomaticpulse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d
    - name: start nginx
      run: docker exec scrapyd service nginx start
    - name: Test
      run: docker exec scrapyd pytest -s --cov-config=.coveragerc --cov=diplomaticpulse diplomaticpulse/tests
    - name: run pylint
      run: docker exec scrapyd pylint /code

